# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabcontents.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(770, 1381)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)

        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")

        self.ofwName = QtWidgets.QLabel(self.tab)
        self.ofwName.setGeometry(QtCore.QRect(48, 242, 79, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ofwName.setFont(font)
        self.ofwName.setObjectName("ofwName")

        self.ofw_name = QtWidgets.QLabel(self.tab)
        self.ofw_name.setGeometry(QtCore.QRect(130, 242, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ofw_name.setFont(font)
        self.ofw_name.setObjectName("ofw_name")

        self.ofwAddress = QtWidgets.QLabel(self.tab)
        self.ofwAddress.setGeometry(QtCore.QRect(66, 267, 60, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ofwAddress.setFont(font)
        self.ofwAddress.setObjectName("ofwAddress")

        self.ofw_address = QtWidgets.QLabel(self.tab)
        self.ofw_address.setGeometry(QtCore.QRect(130, 267, 65, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ofw_address.setFont(font)
        self.ofw_address.setObjectName("ofw_address")

        self.name = QtWidgets.QLabel(self.tab)
        self.name.setGeometry(QtCore.QRect(82, 292, 45, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")

        self.name_ = QtWidgets.QLabel(self.tab)
        self.name_.setGeometry(QtCore.QRect(130, 292, 65, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_.setFont(font)
        self.name_.setObjectName("name_")

        self.address = QtWidgets.QLabel(self.tab)
        self.address.setGeometry(QtCore.QRect(67, 317, 60, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")

        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.address.setFont(font)
        self.address.setObjectName("address")

        self.address_ = QtWidgets.QLabel(self.tab)
        self.address_.setGeometry(QtCore.QRect(130, 317, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.address_.setFont(font)
        self.address_.setObjectName("address_")

        self.pob = QtWidgets.QLabel(self.tab)
        self.pob.setGeometry(QtCore.QRect(36, 342, 92, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pob.setFont(font)
        self.pob.setObjectName("pob")

        self.pob_ = QtWidgets.QLabel(self.tab)
        self.pob_.setGeometry(QtCore.QRect(130, 342, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pob_.setFont(font)
        self.pob_.setObjectName("pob_")

        self.pAddress = QtWidgets.QLabel(self.tab)
        self.pAddress.setGeometry(QtCore.QRect(1, 367, 129, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pAddress.setFont(font)
        self.pAddress.setObjectName("pAddress")

        self.p_address_ = QtWidgets.QLabel(self.tab)
        self.p_address_.setGeometry(QtCore.QRect(130, 367, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.p_address_.setFont(font)
        self.p_address_.setObjectName("p_address_")

        self.dob = QtWidgets.QLabel(self.tab)
        self.dob.setGeometry(QtCore.QRect(43, 392, 86, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dob.setFont(font)
        self.dob.setObjectName("dob")

        self.dob_ = QtWidgets.QLabel(self.tab)
        self.dob_.setGeometry(QtCore.QRect(130, 392, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dob_.setFont(font)
        self.dob_.setObjectName("dob_")

        self.age = QtWidgets.QLabel(self.tab)
        self.age.setGeometry(QtCore.QRect(95, 414, 33, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age.setFont(font)
        self.age.setObjectName("age")

        self.sex = QtWidgets.QLabel(self.tab)
        self.sex.setGeometry(QtCore.QRect(99, 439, 29, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")

        self.religion = QtWidgets.QLabel(self.tab)
        self.religion.setGeometry(QtCore.QRect(68, 461, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.religion.setFont(font)
        self.religion.setObjectName("religion")

        self.contactNo = QtWidgets.QLabel(self.tab)
        self.contactNo.setGeometry(QtCore.QRect(50, 486, 80, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contactNo.setFont(font)
        self.contactNo.setObjectName("contactNo")

        self.email = QtWidgets.QLabel(self.tab)
        self.email.setGeometry(QtCore.QRect(87, 511, 43, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")

        self.tinNo = QtWidgets.QLabel(self.tab)
        self.tinNo.setGeometry(QtCore.QRect(77, 536, 53, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tinNo.setFont(font)
        self.tinNo.setObjectName("tinNo")

        self.age_ = QtWidgets.QLabel(self.tab)
        self.age_.setGeometry(QtCore.QRect(130, 417, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_.setFont(font)
        self.age_.setObjectName("age_")

        self.sex_ = QtWidgets.QLabel(self.tab)
        self.sex_.setGeometry(QtCore.QRect(130, 439, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sex_.setFont(font)
        self.sex_.setObjectName("sex_")

        self.religion_ = QtWidgets.QLabel(self.tab)
        self.religion_.setGeometry(QtCore.QRect(130, 463, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.religion_.setFont(font)
        self.religion_.setObjectName("religion_")

        self.contact_no = QtWidgets.QLabel(self.tab)
        self.contact_no.setGeometry(QtCore.QRect(130, 486, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contact_no.setFont(font)
        self.contact_no.setObjectName("contact_no")

        self.email_ = QtWidgets.QLabel(self.tab)
        self.email_.setGeometry(QtCore.QRect(130, 510, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_.setFont(font)
        self.email_.setObjectName("email_")

        self.tin_no = QtWidgets.QLabel(self.tab)
        self.tin_no.setGeometry(QtCore.QRect(130, 536, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tin_no.setFont(font)
        self.tin_no.setObjectName("tin_no")

        self.citizenship = QtWidgets.QLabel(self.tab)
        self.citizenship.setGeometry(QtCore.QRect(52, 558, 78, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.citizenship.setFont(font)
        self.citizenship.setObjectName("citizenship")

        self.citizenship_ = QtWidgets.QLabel(self.tab)
        self.citizenship_.setGeometry(QtCore.QRect(130, 560, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.citizenship_.setFont(font)
        self.citizenship_.setObjectName("citizenship_")

        self.status = QtWidgets.QLabel(self.tab)
        self.status.setGeometry(QtCore.QRect(50, 583, 78, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setObjectName("status")

        self.status_ = QtWidgets.QLabel(self.tab)
        self.status_.setGeometry(QtCore.QRect(130, 584, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.status_.setFont(font)
        self.status_.setObjectName("status_")

        self.sssNo = QtWidgets.QLabel(self.tab)
        self.sssNo.setGeometry(QtCore.QRect(73, 608, 54, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sssNo.setFont(font)
        self.sssNo.setObjectName("sssNo")

        self.sss_no = QtWidgets.QLabel(self.tab)
        self.sss_no.setGeometry(QtCore.QRect(130, 608, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sss_no.setFont(font)
        self.sss_no.setObjectName("sss_no")

        self.hwName = QtWidgets.QLabel(self.tab)
        self.hwName.setGeometry(QtCore.QRect(10, 633, 142, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hwName.setFont(font)
        self.hwName.setObjectName("hwName")

        self.hwPob = QtWidgets.QLabel(self.tab)
        self.hwPob.setGeometry(QtCore.QRect(59, 658, 92, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hwPob.setFont(font)
        self.hwPob.setObjectName("hwPob")

        self.hw_name = QtWidgets.QLabel(self.tab)
        self.hw_name.setGeometry(QtCore.QRect(154, 634, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hw_name.setFont(font)
        self.hw_name.setObjectName("hw_name")

        self.hw_pob = QtWidgets.QLabel(self.tab)
        self.hw_pob.setGeometry(QtCore.QRect(154, 659, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hw_pob.setFont(font)
        self.hw_pob.setObjectName("hw_pob")

        self.hwDob = QtWidgets.QLabel(self.tab)
        self.hwDob.setGeometry(QtCore.QRect(64, 683, 86, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hwDob.setFont(font)
        self.hwDob.setObjectName("hwDob")

        self.hw_dob = QtWidgets.QLabel(self.tab)
        self.hw_dob.setGeometry(QtCore.QRect(154, 684, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hw_dob.setFont(font)
        self.hw_dob.setObjectName("hw_dob")

        self.hwAge = QtWidgets.QLabel(self.tab)
        self.hwAge.setGeometry(QtCore.QRect(116, 705, 34, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hwAge.setFont(font)
        self.hwAge.setObjectName("hwAge")

        self.hw_age = QtWidgets.QLabel(self.tab)
        self.hw_age.setGeometry(QtCore.QRect(154, 706, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hw_age.setFont(font)
        self.hw_age.setObjectName("hw_age")

        self.occupation = QtWidgets.QLabel(self.tab)
        self.occupation.setGeometry(QtCore.QRect(65, 727, 84, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.occupation.setFont(font)
        self.occupation.setObjectName("occupation")

        self.occupation_ = QtWidgets.QLabel(self.tab)
        self.occupation_.setGeometry(QtCore.QRect(154, 728, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.occupation_.setFont(font)
        self.occupation_.setObjectName("occupation_")

        self.children = QtWidgets.QLabel(self.tab)
        self.children.setGeometry(QtCore.QRect(340, 780, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.children.setFont(font)
        self.children.setObjectName("children")

        self.employerInfo = QtWidgets.QLabel(self.tab)
        self.employerInfo.setGeometry(QtCore.QRect(2, 950, 145, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.employerInfo.setFont(font)
        self.employerInfo.setObjectName("employerInfo")

        self.empName = QtWidgets.QLabel(self.tab)
        self.empName.setGeometry(QtCore.QRect(73, 980, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.empName.setFont(font)
        self.empName.setObjectName("empName")

        self.emp_name = QtWidgets.QLabel(self.tab)
        self.emp_name.setGeometry(QtCore.QRect(120, 981, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emp_name.setFont(font)
        self.emp_name.setObjectName("emp_name")

        self.position = QtWidgets.QLabel(self.tab)
        self.position.setGeometry(QtCore.QRect(63, 1030, 56, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.position.setFont(font)
        self.position.setObjectName("position")

        self.position_ = QtWidgets.QLabel(self.tab)
        self.position_.setGeometry(QtCore.QRect(120, 1030, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.position_.setFont(font)
        self.position_.setObjectName("position_")

        self.empAddress = QtWidgets.QLabel(self.tab)
        self.empAddress.setGeometry(QtCore.QRect(59, 1005, 60, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.empAddress.setFont(font)
        self.empAddress.setObjectName("empAddress")

        self.emp_address = QtWidgets.QLabel(self.tab)
        self.emp_address.setGeometry(QtCore.QRect(120, 1005, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emp_address.setFont(font)
        self.emp_address.setObjectName("emp_address")

        self.empDate = QtWidgets.QLabel(self.tab)
        self.empDate.setGeometry(QtCore.QRect(15, 1079, 106, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.empDate.setFont(font)
        self.empDate.setObjectName("empDate")

        self.emp_date = QtWidgets.QLabel(self.tab)
        self.emp_date.setGeometry(QtCore.QRect(120, 1081, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emp_date.setFont(font)
        self.emp_date.setObjectName("emp_date")

        self.empContactNo = QtWidgets.QLabel(self.tab)
        self.empContactNo.setGeometry(QtCore.QRect(36, 1104, 84, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.empContactNo.setFont(font)
        self.empContactNo.setObjectName("empContactNo")

        self.emp_cn = QtWidgets.QLabel(self.tab)
        self.emp_cn.setGeometry(QtCore.QRect(120, 1105, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emp_cn.setFont(font)
        self.emp_cn.setObjectName("emp_cn")

        self.empEmail = QtWidgets.QLabel(self.tab)
        self.empEmail.setGeometry(QtCore.QRect(77, 1055, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.empEmail.setFont(font)
        self.empEmail.setObjectName("empEmail")

        self.emp_email = QtWidgets.QLabel(self.tab)
        self.emp_email.setGeometry(QtCore.QRect(120, 1056, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emp_email.setFont(font)
        self.emp_email.setObjectName("emp_email")

        self.contactPerson = QtWidgets.QLabel(self.tab)
        self.contactPerson.setGeometry(QtCore.QRect(2, 1160, 262, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contactPerson.setFont(font)
        self.contactPerson.setObjectName("contactPerson")

        self.cpName = QtWidgets.QLabel(self.tab)
        self.cpName.setGeometry(QtCore.QRect(43, 1190, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpName.setFont(font)
        self.cpName.setObjectName("cpName")

        self.cpAddress = QtWidgets.QLabel(self.tab)
        self.cpAddress.setGeometry(QtCore.QRect(29, 1215, 60, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpAddress.setFont(font)
        self.cpAddress.setObjectName("cpAddress")

        self.cpContactNo = QtWidgets.QLabel(self.tab)
        self.cpContactNo.setGeometry(QtCore.QRect(10, 1240, 80, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpContactNo.setFont(font)
        self.cpContactNo.setObjectName("cpContactNo")

        self.opDrName = QtWidgets.QLabel(self.tab)
        self.opDrName.setGeometry(QtCore.QRect(20, 1280, 168, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opDrName.setFont(font)
        self.opDrName.setObjectName("opDrName")

        self.cp_name = QtWidgets.QLabel(self.tab)
        self.cp_name.setGeometry(QtCore.QRect(90, 1190, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cp_name.setFont(font)
        self.cp_name.setObjectName("cp_name")

        self.cp_address = QtWidgets.QLabel(self.tab)
        self.cp_address.setGeometry(QtCore.QRect(90, 1216, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cp_address.setFont(font)
        self.cp_address.setObjectName("cp_address")

        self.cp_cn = QtWidgets.QLabel(self.tab)
        self.cp_cn.setGeometry(QtCore.QRect(90, 1240, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cp_cn.setFont(font)
        self.cp_cn.setObjectName("cp_cn")

        self.opdr_name = QtWidgets.QLabel(self.tab)
        self.opdr_name.setGeometry(QtCore.QRect(191, 1282, 63, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opdr_name.setFont(font)
        self.opdr_name.setObjectName("opdr_name")
        TabWidget.addTab(self.tab, "")

        self.retranslateUi(TabWidget)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.ofwName.setText(_translate("TabWidget", "OFW Name:"))
        self.ofw_name.setText(_translate("TabWidget", "TextLabel"))
        self.ofwAddress.setText(_translate("TabWidget", "Address:"))
        self.ofw_address.setText(_translate("TabWidget", "TextLabel"))
        self.name.setText(_translate("TabWidget", "Name:"))
        self.name_.setText(_translate("TabWidget", "TextLabel"))
        self.address.setText(_translate("TabWidget", "Address:"))
        self.address_.setText(_translate("TabWidget", "TextLabel"))
        self.pob.setText(_translate("TabWidget", "Place of Birth:"))
        self.pob_.setText(_translate("TabWidget", "TextLabel"))
        self.pAddress.setText(_translate("TabWidget", "Provincial Address:"))
        self.p_address_.setText(_translate("TabWidget", "TextLabel"))
        self.dob.setText(_translate("TabWidget", "Date of Birth:"))
        self.dob_.setText(_translate("TabWidget", "TextLabel"))
        self.age.setText(_translate("TabWidget", "Age:"))
        self.sex.setText(_translate("TabWidget", "Sex:"))
        self.religion.setText(_translate("TabWidget", "Religion:"))
        self.contactNo.setText(_translate("TabWidget", "Contact No:"))
        self.email.setText(_translate("TabWidget", "Email:"))
        self.tinNo.setText(_translate("TabWidget", "TIN No.:"))
        self.age_.setText(_translate("TabWidget", "TextLabel"))
        self.sex_.setText(_translate("TabWidget", "TextLabel"))
        self.religion_.setText(_translate("TabWidget", "TextLabel"))
        self.contact_no.setText(_translate("TabWidget", "TextLabel"))
        self.email_.setText(_translate("TabWidget", "TextLabel"))
        self.tin_no.setText(_translate("TabWidget", "TextLabel"))
        self.citizenship.setText(_translate("TabWidget", "Citizenship:"))
        self.citizenship_.setText(_translate("TabWidget", "TextLabel"))
        self.status.setText(_translate("TabWidget", "Civil Status:"))
        self.status_.setText(_translate("TabWidget", "TextLabel"))
        self.sssNo.setText(_translate("TabWidget", "SSS No.:"))
        self.sss_no.setText(_translate("TabWidget", "TextLabel"))
        self.hwName.setText(_translate("TabWidget", "Husband/Wife Name:"))
        self.hwPob.setText(_translate("TabWidget", "Place of Birth:"))
        self.hw_name.setText(_translate("TabWidget", "TextLabel"))
        self.hw_pob.setText(_translate("TabWidget", "TextLabel"))
        self.hwDob.setText(_translate("TabWidget", "Date of Birth:"))
        self.hw_dob.setText(_translate("TabWidget", "TextLabel"))
        self.hwAge.setText(_translate("TabWidget", "Age:"))
        self.hw_age.setText(_translate("TabWidget", "TextLabel"))
        self.occupation.setText(_translate("TabWidget", "Occupation:"))
        self.occupation_.setText(_translate("TabWidget", "TextLabel"))
        self.children.setText(_translate("TabWidget", "Children"))
        self.employerInfo.setText(_translate("TabWidget", "Employer Information:"))
        self.empName.setText(_translate("TabWidget", "Name:"))
        self.emp_name.setText(_translate("TabWidget", "TextLabel"))
        self.position.setText(_translate("TabWidget", "Position:"))
        self.position_.setText(_translate("TabWidget", "TextLabel"))
        self.empAddress.setText(_translate("TabWidget", "Address:"))
        self.emp_address.setText(_translate("TabWidget", "TextLabel"))
        self.empDate.setText(_translate("TabWidget", "Date Employed:"))
        self.emp_date.setText(_translate("TabWidget", "TextLabel"))
        self.empContactNo.setText(_translate("TabWidget", "Contact No.:"))
        self.emp_cn.setText(_translate("TabWidget", "TextLabel"))
        self.empEmail.setText(_translate("TabWidget", "Email:"))
        self.emp_email.setText(_translate("TabWidget", "TextLabel"))
        self.contactPerson.setText(_translate("TabWidget", "Person to contact in case of Emergency:"))
        self.cpName.setText(_translate("TabWidget", "Name:"))
        self.cpAddress.setText(_translate("TabWidget", "Address:"))
        self.cpContactNo.setText(_translate("TabWidget", "Contact No:"))
        self.opDrName.setText(_translate("TabWidget", "Operator or Driver Name:"))
        self.cp_name.setText(_translate("TabWidget", "TextLabel"))
        self.cp_address.setText(_translate("TabWidget", "TextLabel"))
        self.cp_cn.setText(_translate("TabWidget", "TextLabel"))
        self.opdr_name.setText(_translate("TabWidget", "TextLabel"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
